export default {
  bandDesc: {
    transcendence: 'The domain of beauty, sublimation, and sacred geometry. Veils, Cherry Blossoms, Mandalas, and Sacred Heart reside here. Coordinates of this band: a return from delegated authorship to the hand, explicit citation of mono no aware, and traversal of Catholic and Buddhist iconographies. The painting period (2018–) carries Bonnard\'s and Seurat\'s pointillism into the 21st century — a self-critique after the Diamond Skull and a recovery of hand and time.',
    system: 'The domain of taxonomy, grid, and industry. Spot Paintings, the Pharmacy cabinets, the Last Supper drug packaging, and the medical-theological fusion of Trinity reside here. On the lineage of Sol LeWitt\'s instruction art and Warhol\'s Factory delegation, pharmaceutical taxonomy operates as the 21st century\'s Latin — pill as host, label as color chart.',
    ritual: 'The domain of rite, the ephemeral, and the cycle. Spin Paintings\' centrifugal chance, the Butterfly\'s life/death binary, and The Currency\'s NFT-painting either/or reside here. Operating not as a single work but as infinite series — the 21st-century transposition of rosary, prayer, and Mass.',
    vanitas: 'The domain of vanitas, dissolution, and market fracture. For the Love of God (the Diamond Skull), the Sotheby\'s auction of September 15, 2008 (in coincidence with Lehman), the apocryphal ambition of Treasures, and the dead-fly monochromes of Black Sun. The capitalist literalization of the 17th-century Dutch vanitas tradition. Coordinates where Hirst\'s own ambition becomes the meta-realization of vanitas.',
    mortality: 'The domain of confronting death. The Physical Impossibility of Death (Shark), Mother and Child Divided, A Thousand Years, Away from the Flock. The impossibility of knowing death through experience, struck head-on with museum vitrines and formaldehyde. The 1991 Saatchi-commissioned Shark is the turning point of 21st-century art and the propositional origin of Hirst\'s entire oeuvre.',
  },
};
